### ISSUE TITLE
feature files

### ISSUE THREAD

**Issue by daodaofr** [xumingze0308/TRN.pytorch#1]
Thanks for your great work.

Would you please upload the feature files (.npy) for THUMOS'14 dataset so we can directly run your code?

Thanks.

**Comment by xumingze0308** [comment]
Thanks for reaching out. However, we don't have any plan to release the THUMOS'14 features. Please follow the instruction here: https://github.com/yjxiong/anet2016-cuhk to extract features accordingly.
