### ISSUE TITLE
Where to find data/HDD/inceptionresnetv2/201703011016.npy? 

### ISSUE THREAD

**Issue by danhlephuoc** [xumingze0308/TRN.pytorch#15]
We ran into this error with HDD dataset, 

FileNotFoundError: [Errno 2] No such file or directory: 'data/HDD/inceptionresnetv2/201703011016.npy'

I wonder where to get the 201703011016.npy file?

**Comment by xumingze0308** [comment]
You need to contact Honda Research to get the HDD dataset.

**Comment by danhlephuoc** [comment]
Yes, I contacted Honda Research to download the dataset, but I could not find the data for the sub direction HDD/inceptionresnetv2...

**Comment by xumingze0308** [comment]
"inceptionresnetv2" are the extracted features from RGB frames using InceptionResnetV2 (pretrained on ImageNet). If Honda didn't provide that, you need to extract the features by yourself.
