### ISSUE TITLE
LSTR code release?

### ISSUE THREAD

**Issue by g1910** [xumingze0308/TRN.pytorch#16]
Hi,

First of, thanks for making TRN's code available. Will you also be release the code for LSTR?

Thanks

**Comment by xumingze0308** [comment]
Thanks for your interest. We will probably release the code for LSTR, but it could take some time to follow the company policy.

**Comment by xumingze0308** [comment]
The code of LSTR is released here: https://github.com/amazon-research/long-short-term-transformer.
