### ISSUE TITLE
What is the ``random chop of`` in dataset used for ?

### ISSUE THREAD

**Issue by SCZwangxiao** [xumingze0308/TRN.pytorch#19]
Hi Mingze:
I was reading the code in ```lib/datasets/thumos_data_layer.py```, and found there is a ```seed``` the following code:
```python
seed = np.random.randint(self.enc_steps) if self.training else 0
for start, end in zip(
    range(seed, target.shape[0] - self.dec_steps, self.enc_steps),
    range(seed + self.enc_steps, target.shape[0] - self.dec_steps, self.enc_steps)):
    enc_target = target[start:end]
    dec_target = self.get_dec_target(target[start:end + self.dec_steps])
    self.inputs.append([
        session, start, end, sensor[start:end],
        enc_target, dec_target,
        ])
```
I think it could be some sort of data augmentation ?
If so, what's the purpose of the ```seed``` ? Why its maximum should be ```self.enc_steps```?

**Comment by xumingze0308** [comment]
This may not be a good name, but yes it's the data augmentation (random chop of) that we described in paper's Section 4.2. It randomly chopped several frames from the beginning of each video, which makes the training samples in each epoch are slightly different.
