### ISSUE TITLE
Extract feature representations for THUMOS'14 dataset

### ISSUE THREAD

**Issue by dmvictor** [xumingze0308/TRN.pytorch#2]
I try to extract feature representations for THUMOS'14 dataset by following this [repo](https://github.com/yjxiong/anet2016-cuhk). In the [repo](https://github.com/yjxiong/anet2016-cuhk), OpenCV's version is 2.4.13, and the Caffe's version is their specified version. My GPU is Nvidia GeForce RTX 2060, I install CUDA 10.0 and cuDNN 7.6.4 for GPU acceleration. I found out that I could not build OpenCV 2.4.13 in my environment. Therefore, I built OpenCV 4.1.0 and denseflow by following this [comment](https://github.com/open-mmlab/mmaction/issues/9#issuecomment-505944010). And I built Caffe from the official [repo](https://github.com/BVLC/caffe). When I run the example 
```python examples/classify_video.py data/plastering.avi```
, I met the [caffe.LayerParameter issue](https://github.com/yjxiong/anet2016-cuhk/issues/2). I tried to build the specified version Caffe with no luck. I have noticed that your code is developed with CUDA 9.0 and Python 3.6. I suppose you have met similar environment issues because the [repo](https://github.com/yjxiong/anet2016-cuhk) is developed with Python 2. Would you mind sharing how you solved the Caffe LayerParameter issue? Thank you!

**Comment by xumingze0308** [comment]
I don't think we had this problem, because, when extracting features for THUMOS'14, we followed the repo and set up the same environment (e.g., Python and OpenCV version). I would suggest to create another environment with Python 2 and contact the [authors](https://github.com/yjxiong/anet2016-cuhk) if there are still some problems.

**Comment by dmvictor** [comment]
Because my GPU is Nvidia GeForce RTX 2060, which is Turing architecture. Therefore, I install CUDA 10.0 according to this [thread](https://devtalk.nvidia.com/default/topic/1055573/cuda-setup-and-installation/does-cuda-9-0-support-rtx-2060-/). CUDA 10.0 seems to have incompatible issues with OpenCV 2.4.13 and the specified version of Caffe. If I have to set up the same environment as the [author](https://github.com/yjxiong/anet2016-cuhk), I think I have to find another machine to do so. May I ask your OS version and CUDA version for extracting feature representations for THUMOS'14 dataset? Thank you!

**Comment by xumingze0308** [comment]
We used CUDA 9.0 and the GPU is Nvidia Quadro P6000.
