### ISSUE TITLE
Camer feature (inceptionresnetv2/ 201702271017.npy) not found in the HDD dataset

### ISSUE THREAD

**Issue by pgupta119** [xumingze0308/TRN.pytorch#20]
From Where I can get the  inceptionresnetv2/ 201702271017.npy , I have access to the HDD dataset but I couldn't find the camera feature data.

**Comment by xumingze0308** [comment]
You need to contact Honda Research to get our extracted features. Otherwise, you may have to extract them yourselves.

**Comment by pgupta119** [comment]
Would it be possible to share the code of the extract features?  I have images of each video.

**Comment by xumingze0308** [comment]
I directly used their extracted features when I did my internship in HRI, so I don't have available code for that. But I don't think they use any specific tricks but just a normal feature extraction.

**Comment by pgupta119** [comment]
okay,  thanks a lot, I will do it myself
