### ISSUE TITLE
Problem when running anet2016

### ISSUE THREAD

**Issue by zhujiatong** [xumingze0308/TRN.pytorch#3]
Hello, I followed your instructions to first run the code posed by yjxiong to extract features, but I found that when I run his code, there is always a problem of "ANET_HOME" and "ANET_CFG", it seems that they are not in environment, did you meet this problem when extracting features, and if I use that code to extract features of THUMOS14, do I need to change his code? It seems his code is suitable for ActivityNet, thank you a lot!

**Comment by xumingze0308** [comment]
I don't remember we had this problem. It seems "ANET_HOME" and "ANET_CFG" are the path and config files (respectively) of ActivityNet. I think you could be able to check in the code where these variables are used in the code and solve the problem accordingly.

**Comment by zhujiatong** [comment]
Thank you a lot, I have already run the code successfully,but I still have a question that are those ".npy" files in your database come from the "anet2016"? How do you exactly use that code to extract features from RGB and optical flow? Thanks!

**Comment by zhujiatong** [comment]
Excuse me, but I found the size of output of "global pool"  is (10,1024,1,1), so how do you make the "npy" of bn_inception become (L*1024)?Thank you!

**Comment by xumingze0308** [comment]
(1) The output size 10 is the batch size and 1024 is the feature size. For more details about feature extraction, please refer the 4.3 Section of our paper.

(2) We directly extracted video frames with 24 fps, and L is the number of video frames.
