### ISSUE TITLE
Train RGB ResNet-200 model for THUMOS'14 dataset

### ISSUE THREAD

**Issue by dmvictor** [xumingze0308/TRN.pytorch#5]
I want to train the ResNet-200 model on my RGB dataset which consists of 22 classes as you mentioned before. When I run the classification with my RGB model, I met the "ShapeEquals(proto) shape mismatch (reshape not set)" problem.

```
python examples/classify_video.py data/plastering.avi
```

```
I0209 13:13:38.996109   596 net.cpp:241] caffe.ReLU_3 does not need backward computation.
I0209 13:13:38.996112   596 net.cpp:241] caffe.BN_2 does not need backward computation.
I0209 13:13:38.996116   596 net.cpp:241] caffe.Pooling_1_caffe.Pooling_1_0_split does not need backward computation.
I0209 13:13:38.996119   596 net.cpp:241] caffe.Pooling_1 does not need backward computation.
I0209 13:13:38.996124   596 net.cpp:241] caffe.SpatialConvolution_0 does not need backward computation.
I0209 13:13:38.996126   596 net.cpp:282] This network produces output fc-action
I0209 13:13:38.996475   596 net.cpp:531] Collecting Learning Rate and Weight Decay.
I0209 13:13:38.996541   596 net.cpp:294] Network initialization done.
I0209 13:13:38.996544   596 net.cpp:295] Memory required for data: 611862616
F0209 13:13:39.116333   596 blob.cpp:455] Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
*** Check failure stack trace: ***
Aborted (core dumped)
```

[resnet200_anet_2016_22_deploy.prototxt](https://gist.github.com/dmvictor/54a4f67e6021f45877446456607ed28e) is my prototxt for running the classification. 
[tsn_resnet200_rgb_train_val.prototxt](https://gist.github.com/dmvictor/66ab6e0ec6ff674600a791a070e567dc) is my prototxt for training TSN model. The first part of my my prototxt for training, including "data" and "reshape_data" layer is referenced from [tsn_bn_inception_rgb_train_val.prototxt](https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_train_val.prototxt). The second part, the layers between "caffe.SpatialConvolution_0" and "caffe.Flatten_673", is referenced from [resnet200_anet_2016_deploy.prototxt](http://yjxiong.blob.core.windows.net/anet-2016/resnet200_anet_2016_deploy.prototxt). And the third part, including layers after "caffe.Flatten_673" is referenced from this [issue](https://github.com/yjxiong/anet2016-cuhk/issues/6). 

Actually, I asked the question over [here](https://github.com/yjxiong/anet2016-cuhk/issues/6#issuecomment-582874387) in anet2016-cuhk. No response so far. Could you give me some directions for setting the prototxt? I think the problem should be in the first part or third part, but I have no idea which layer goes wrong. Sorry for bothering, but this problem really stuck me for a period of time. Thank you!

**Comment by xumingze0308** [comment]
MMAction2 provides ANet pretrained ResNet-50 in PyTorch, which may be much easier to use. The performance gap between ResNet-200 and ResNet-50 shouldn't be too large based on my experiments.
