### ISSUE TITLE
Another question to thumos14 and tvseries dataset,thanks

### ISSUE THREAD

**Issue by zhujiatong** [xumingze0308/TRN.pytorch#6]
Excuse me , but I want to know that whether you changed the fps of videos in thumos14 dataset,since the original fps of the video is 30 and what you mentioned in your articles is that the fps is 24.Another question is that is the axis 0 of camera inputs minus the axis 0 of motions inputs is 5?For example,the camera inputs is (200,22),the motion inputs is (195,22),is that correct?Thank you a lot!

**Comment by xumingze0308** [comment]
(1) Yes, we followed prior work and used fps 24 on THUMOS'14 dataset.
(2) No, the camera and motion inputs should have the same temporal dimension (axis 0).
Please refer to paper's Section 4.3. for more details.
