### ISSUE TITLE
About the number L of features in npy files

### ISSUE THREAD

**Issue by 232525** [xumingze0308/TRN.pytorch#7]
Thanks for your excellent work, I have a question about the prepared data format. Assume a 5 seconds video with fps 24, it has total 5\*24=120 original frames, so is the L is 5\*4=20? so the actually inputs of the video are 20 frames (or chunks)?

**Comment by xumingze0308** [comment]
Yes, I think that's correct.

**Comment by 232525** [comment]
> Yes, I think that's correct.

thanks for your reply!
