### ISSUE TITLE
End to End Training

### ISSUE THREAD

**Issue by ShechemKS** [xumingze0308/TRN.pytorch#8]
Your paper mentions that training was conducted in an end-to-end manner. However, the pytorch code does not link the feature extraction models to the TRN model. Were the feature extraction models that you used fine-tuned on the THUMOS or HDD Datasets, or were the pre-trained ImageNet weights used?

If they were fine-tuned, were they fine-tuned separately, treating each image as a classification problem, or were they linked to the TRN and trained as part of the TRN training, end-to-end?

Thank you.

**Comment by xumingze0308** [comment]
We followed prior work and didn't finetune the feature extractors. TRN itself is end-to-end training. Our paper's 4.3 Section has mentioned details about models and pretrained datasets we used for HDD and THUMOS.
